### ISSUE TITLE
Another pull request

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [grussell86/shared-code#2]
I hope it's OK that I mess around with your code.  It's SO nice to see nicely laid out GUIs like yours. Heck, it's nice to see ANY GUIs made with the package.  You really are doing a nice job 👍

**Comment by grussell86** [comment]
Please feel free to do so.  I just replaced the dependency on the Linux package 'sox' for sound with a Python package called 'playsound' which works on Windows and Linux.  I plan on creating a new version with reduced Linux command-line dependencies.

I'm pretty new to GitHub, so how do I approve your pull request?

**Comment by MikeTheWatchGuy** [comment]
Click pull request tab... then click on the pull request itself.

Hopefully there will be no conflicts.  If so you'll see a series of green buttons that you'll click. 3 in total I think

**Comment by MikeTheWatchGuy** [comment]
My Demo_Button_Click uses playsound out of the winsound package. Is it the same?

```
import PySimpleGUI as sg
import winsound


sg.ChangeLookAndFeel('Dark')
sg.SetOptions(element_padding=(0,0))

layout = [
          [sg.ReadFormButton('Start', button_color=('white', 'black'), key='start'),
           sg.ReadFormButton('Stop', button_color=('white', 'black'), key='stop'),
           sg.ReadFormButton('Reset', button_color=('white', 'firebrick3'), key='reset'),
           sg.ReadFormButton('Submit', button_color=('white', 'springgreen4'), key='submit')]
          ]

form = sg.FlexForm("Button Click", default_element_size=(12,1), text_justification='r', auto_size_text=False, auto_size_buttons=False, default_button_element_size=(12,1)).Layout(layout).Finalize()

form.FindElement('submit').Update(disabled=True)

recording = have_data = False
while True:
    button, values = form.Read()
    if button is None:
        exit(69)
    winsound.PlaySound("ButtonClick.wav", 1)

```

**Comment by grussell86** [comment]
winsound only works on Windows while playsound works on Linux and Windows.  It's pretty slick.

from playsound import playsound
playsound("ButtonClick.wav")
